name: Playwright Test

on:
  push:
    branches:
      - main     
      
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 

      - name: Instalar dependências
        run: |
          npm ci

      - name: Executar testes Playwright
        run: |
          npm run test